#:kivy 2.3.1

<ToDoListScreen>
    md_bg_color: app.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(20)
        MDLabel:
            text: "Coming Soon"
            size_hint_x: 1
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            font_style: 'Title'
            role: 'large'
            text_color: app.theme_cls.primaryColor
            bold: True